# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org:
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  test:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  overview:
    handler: functions/bookingOverview/index.handler
    events:
      - httpApi:
          path: /overview
          method: get
  availableRooms:
    handler: functions/getAvailableRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: get
  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: /room
          method: post
  deleteRoom:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: /room
          method: delete
  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /room/{id}
          method: put

resources:
  Resources:
    roomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bonzai_rooms
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    bookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bonzai_bookings
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
